name: Tests and Checks

on: [push]

jobs:
  python-linting-and-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
            
          # macOS and Windows should only run Python 3.11 (save compute power).
          - os: macos-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint with Ruff
        run: |
          ruff version
          ruff check cts1_ground_support/
      - name: Type check with Pyright
        run: |
          pyright .
      - name: Unit test with pytest
        run: |
          coverage run -m pytest tests/ -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
