name: Tests and Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-linting-and-unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13"

          # macOS and Windows should only run Python 3.11 (save compute power).
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check .

      - name: Type check with Pyright
        run: uv run pyright .

      - name: Unit test with pytest
        run: |
          uv run coverage run -m pytest tests/ -v -s

      - name: Generate Coverage Report
        run: uv run coverage report -m
